server:
  port: 9595
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka,http://peer2:8002/eureka
  instance:
    hostname: gateway
spring:
  application:
    name: microservice-api-gateway

# 对 服务提供者进行映射 （自定义路径）
zuul:
  routes:
    user: # 随便写，唯一既可
      path: /user-ribbon/**
      service-id: microservice-consumer-movie-ribbon
  # 忽略不想被路径的服务
  ignored-services: microservice-provider-user
