
server:
  port: 6868
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liaosc-ai/spirngcloud-study/
          search-paths: config-repo
          username:
          password:

