spring:
  application:
    name: eureka-server
  profiles:
    active: peer1
---
spring:
  profiles: peer1
server:
  port: 8001
eureka:
  instance:
    hostname: peer1
  client:
    # 禁止注册自己
    #register-with-eureka: true
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://peer2:8002/eureka/


---
spring:
  profiles: peer2
server:
  port: 8002
eureka:
  instance:
    hostname: peer2
  client:
    #register-with-eureka=false 禁止注册自己
    #register-with-eureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/

